categories = [
    {"name": "Casa", "color": "#2980B9", "icon": "home"},
    {"name": "Eletrônicos", "color": "#9B59B6", "icon": "tv"},
    {"name": "Alimentação", "color": "#E67E22", "icon": "utensils"},
    {"name": "Lanche", "color": "#F39C12", "icon": "utensils"},
    {"name": "Pet", "color": "#2ECC71", "icon": "paw"},
    {"name": "Saúde", "color": "#C0392B", "icon": "heartbeat"},
    {"name": "Transporte", "color": "#8E44AD", "icon": "car"},
    {"name": "Cartão", "color": "#34495E", "icon": "credit-card"},
    {"name": "Roupa", "color": "#16A085", "icon": "shirt"},
    {"name": "Carro", "color": "#1ABC9C", "icon": "car"},
    {"name": "Manutenção", "color": "#7D3C98", "icon": "tool"},
    {"name": "Viagem", "color": "#5DADE2", "icon": "airplane"},
    {"name": "Presente", "color": "#E74C3C", "icon": "gift"},
    {"name": "Filhos", "color": "#F1C40F", "icon": "children"},
    {"name": "Educação", "color": "#7FB3D5", "icon": "book"},
    {"name": "Beleza", "color": "#F1948A", "icon": "scissors"},
    {"name": "Telefone", "color": "#AF7AC5", "icon": "phone"},
    {"name": "Internet", "color": "#48C9B0", "icon": "wifi"},
    {"name": "Jogos", "color": "#DC7633", "icon": "game"},
    {"name": "Esportes", "color": "#52BE80", "icon": "ball"},
    {"name": "Outros", "color": "#95A5A6", "icon": "question"},
]
